### ISSUE TITLE
Trinkets support

### ISSUE THREAD

**Issue by p3lim** [WerDei/Zoomglass#3]
Would be nice if support for [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets) would be added, in a legs/belt slot, then the keybind would use the spyglass directly from there.

**Comment by WerDei** [comment]
Most likely not going to happen - this mod works by simply swapping inventory slots around, to make it compatible with unmodded servers. If I had to make a version of this mod that doesn't need to be (and thus can take advantage of Trinkets/Curios/etc.), I'd also need to rewrite it to do something better, and at this point it's easier just to make a new mod.

I'm not against this idea, and I would like to do it somewhere in the future - it would also be a good opportunity to fix one very annoying vanilla bug. But as I said, if I make it, it would probably just be a separate mod

**Comment by p3lim** [comment]
Fair enough, the only benefit to the support in practice would be an inventory slot saved, as this mod works great already. Thanks for the consideration and understandable response.
