### ISSUE TITLE
Put spyglass back in slot

### ISSUE THREAD

**Issue by christoros** [WerDei/Zoomglass#5]
It would be nice if the mod would put the spyglass back in the slot it was in before zooming, instead of leaving it in the hotbar.

**Comment by WerDei** [comment]
Interesting, the mod should already be doing that. If you don't mind, can you specify what Minecraft versoin are you using, and what other mods you have installed?

**Comment by christoros** [comment]
It seems as I have been hasty in my conclusions. Though it does put the spyglass back in it's slot when it is replacing an item in the hotbar, it keeps it's spot in the hotbar when you zoom with an empty slot in hand. Though this might be on purpose, personally I would like it better if it went back into my inventory. Thank you for the quick reply and keep up the good work!

**Comment by WerDei** [comment]
I wasn't able to reproduce the issue I'm afraid. If you could follow up with more info, like the list of other mods you have installed, it would be mich appreciated!
