### ISSUE TITLE
ear candy

### ISSUE THREAD

**Issue by slovinsqui** [WerDei/Zoomglass#6]
missing sound when pressing Z to use spyglass, plus adding clicking sounds when zooming in and out would be nice

**Comment by WerDei** [comment]
There's no sound when using it in creative/spectator, yes (as it's not actually using an item), I might change that. Zoomglass does not have zoom in/out functionality though, it's probably from another mod you're using,

**Comment by WerDei** [comment]
Added sounds for a fake spyglass. Better late than never, I guess?
