### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by paneeka** [WerDei/Zoomglass#8]
In the mod menu, the mod itself is displayed, but there is no "zoom *select the * key" in the settings

**Comment by WerDei** [comment]
Just to clarify, the option is called "Quick Spyglass" and you can find it in the kyebinds menu, under "Inventory" section:
![image](https://github.com/WerDei/Zoomglass/assets/48105614/86bcec8a-c2e5-4d5d-a051-dc775dd99742)

If you don't see it and pressing `z` does nothing, then please provide more information - your Minecraft and Zoomgalss versions, list of other mods you have installed, etc.
