### ISSUE TITLE
Spyglass Use not render for other Players on SwapSlot

### ISSUE THREAD

**Issue by SoulxluoS** [WerDei/Zoomglass#9]
Hi, Thank you for good mod.

To do this, when using the item, need to add a delay, apparently so that the server has time to read. 
![image](https://github.com/user-attachments/assets/bb5ff93b-c320-481a-95f2-b1e897a3d065)

**Comment by WerDei** [comment]
Yes, I remember encountering this issue when first developing the mod. In the end I decided that I'd rather have no delay, just to make the swap button feel more responsive. But I'll consider re-adding it, when I go back to playing and modding Minecraft.

**Comment by WerDei** [comment]
Managed to figure out a good solution - spyglass is used immediately on client, but it only tells the server about it after a delay. This way it both feels snappy, and doesn't cause a boken animation.
